# Use a lightweight Python image
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Copy project files into container
COPY . /app

# Default command to run your emulator
CMD ["python", "main.py"]