---
- name: Server Deployment Playbook
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: Update APT Cache
    ansible.builtin.apt:
      update_cache: true
      upgrade: true

  - name: Install packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - curl
      - vim
      - mosquitto
      - mosquitto-clients
      - nginx
      - python3
      - git
      - pip
      - python3-psutil

  - name: Clone the repo
    ansible.builtin.git:
      repo: 'https://github.com/cantr1/ProfessionalPortfolio.git'
      dest: /home/kelz/ProfessionalPortfolio
      version: main
      update: true

  - name: Copy Mosquitto Conf for MQTT
    ansible.builtin.copy:
      src: /home/kelz/ProfessionalPortfolio/GoHelper/resources/mosquitto.conf
      path: /etc/mosquitto/mosquitto.conf
      owner: root
      group: root
      mode: '0644'
      remote_src: true

  - name: Copy HTML file for Nginx
    ansible.builtin.copy:
      src: /home/kelz/ProfessionalPortfolio/GoHelper/resources/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
      remote_src: true

  - name: Enable services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - nginx
      - mosquitto

  - name: Copy Python script for MQTT Reporting
    ansible.builtin.copy:
      src: /home/kelz/ProfessionalPortfolio/GoHelper/resources/system_data.py
      dest: /home/kelz/system_data.py
      owner: kelz
      group: kelz
      mode: '0700'
      remote_src: true

  - name: Setup Cron Job for MQTT Reporting
    ansible.builtin.cron:
      name: Publish System Data to MQTT Broker
      minute: "*"
      user: root
      job: mosquitto_pub -t system/"$(hostname)" -m "$(python3 /home/kelz/system_data.py)" -h 192.168.1.124 -p 1883

  - name: Copy Python script for Nginx Reporting
    ansible.builtin.copy:
      src: /home/kelz/ProfessionalPortfolio/GoHelper/resources/pub_json.py
      dest: /home/kelz/pub_json.py
      owner: kelz
      group: kelz
      mode: '0700'
      remote_src: true

  - name: Setup Cron Job for Nginx Reporting
    ansible.builtin.cron:
      name: Publish System Data to Nginx
      minute: "*"
      user: root
      job: /usr/bin/python3 /home/kelz/pub_json.py