---
- name: Install and configure Apache web server
  hosts: localhost
  become: true

  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Enable and start Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Remove default /var/www/html directory
      file:
        path: /var/www/html
        state: absent

    - name: Create symlink from /tftpboot to /var/www/html
      file:
        src: /tftpboot
        dest: /var/www/html
        state: link
