---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
