// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExerciseSession = `-- name: CreateExerciseSession :one
INSERT INTO exercise_sessions (id, created_at, updated_at, workout_start, workout_end, workout_name, zone1_mins, zone2_mins, zone3_mins, strain, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, workout_start, workout_end, workout_name, zone1_mins, zone2_mins, zone3_mins, strain, user_id
`

type CreateExerciseSessionParams struct {
	WorkoutStart time.Time
	WorkoutEnd   time.Time
	WorkoutName  string
	Zone1Mins    int32
	Zone2Mins    int32
	Zone3Mins    int32
	Strain       int32
	UserID       uuid.UUID
}

func (q *Queries) CreateExerciseSession(ctx context.Context, arg CreateExerciseSessionParams) (ExerciseSession, error) {
	row := q.db.QueryRowContext(ctx, createExerciseSession,
		arg.WorkoutStart,
		arg.WorkoutEnd,
		arg.WorkoutName,
		arg.Zone1Mins,
		arg.Zone2Mins,
		arg.Zone3Mins,
		arg.Strain,
		arg.UserID,
	)
	var i ExerciseSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkoutStart,
		&i.WorkoutEnd,
		&i.WorkoutName,
		&i.Zone1Mins,
		&i.Zone2Mins,
		&i.Zone3Mins,
		&i.Strain,
		&i.UserID,
	)
	return i, err
}

const queryExerciseSessions = `-- name: QueryExerciseSessions :one
SELECT id, created_at, updated_at, workout_start, workout_end, workout_name, zone1_mins, zone2_mins, zone3_mins, strain, user_id FROM exercise_sessions WHERE id = $1
`

func (q *Queries) QueryExerciseSessions(ctx context.Context, id uuid.UUID) (ExerciseSession, error) {
	row := q.db.QueryRowContext(ctx, queryExerciseSessions, id)
	var i ExerciseSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkoutStart,
		&i.WorkoutEnd,
		&i.WorkoutName,
		&i.Zone1Mins,
		&i.Zone2Mins,
		&i.Zone3Mins,
		&i.Strain,
		&i.UserID,
	)
	return i, err
}

const queryUserExercieSessions = `-- name: QueryUserExercieSessions :many
SELECT id, created_at, updated_at, workout_start, workout_end, workout_name, zone1_mins, zone2_mins, zone3_mins, strain, user_id FROM exercise_sessions WHERE user_id = $1
`

func (q *Queries) QueryUserExercieSessions(ctx context.Context, userID uuid.UUID) ([]ExerciseSession, error) {
	rows, err := q.db.QueryContext(ctx, queryUserExercieSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSession
	for rows.Next() {
		var i ExerciseSession
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkoutStart,
			&i.WorkoutEnd,
			&i.WorkoutName,
			&i.Zone1Mins,
			&i.Zone2Mins,
			&i.Zone3Mins,
			&i.Strain,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeExercises = `-- name: RemoveExercises :exec
DELETE FROM exercise_sessions
`

func (q *Queries) RemoveExercises(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeExercises)
	return err
}
