// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meditations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMeditationSession = `-- name: CreateMeditationSession :one
INSERT INTO meditation_sessions (id, created_at, updated_at, meditation_start, meditation_end, starting_hr, ending_hr, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, meditation_start, meditation_end, starting_hr, ending_hr, user_id
`

type CreateMeditationSessionParams struct {
	MeditationStart time.Time
	MeditationEnd   time.Time
	StartingHr      int32
	EndingHr        int32
	UserID          uuid.UUID
}

func (q *Queries) CreateMeditationSession(ctx context.Context, arg CreateMeditationSessionParams) (MeditationSession, error) {
	row := q.db.QueryRowContext(ctx, createMeditationSession,
		arg.MeditationStart,
		arg.MeditationEnd,
		arg.StartingHr,
		arg.EndingHr,
		arg.UserID,
	)
	var i MeditationSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeditationStart,
		&i.MeditationEnd,
		&i.StartingHr,
		&i.EndingHr,
		&i.UserID,
	)
	return i, err
}

const meditationSession = `-- name: MeditationSession :one
SELECT id, created_at, updated_at, meditation_start, meditation_end, starting_hr, ending_hr, user_id FROM meditation_sessions WHERE id = $1
`

func (q *Queries) MeditationSession(ctx context.Context, id uuid.UUID) (MeditationSession, error) {
	row := q.db.QueryRowContext(ctx, meditationSession, id)
	var i MeditationSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeditationStart,
		&i.MeditationEnd,
		&i.StartingHr,
		&i.EndingHr,
		&i.UserID,
	)
	return i, err
}

const queryUserMeditationSessions = `-- name: QueryUserMeditationSessions :many
SELECT id, created_at, updated_at, meditation_start, meditation_end, starting_hr, ending_hr, user_id FROM meditation_sessions WHERE user_id = $1
`

func (q *Queries) QueryUserMeditationSessions(ctx context.Context, userID uuid.UUID) ([]MeditationSession, error) {
	rows, err := q.db.QueryContext(ctx, queryUserMeditationSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeditationSession
	for rows.Next() {
		var i MeditationSession
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeditationStart,
			&i.MeditationEnd,
			&i.StartingHr,
			&i.EndingHr,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMeditations = `-- name: RemoveMeditations :exec
DELETE FROM meditation_sessions
`

func (q *Queries) RemoveMeditations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeMeditations)
	return err
}
