// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ExerciseSession struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	WorkoutStart time.Time
	WorkoutEnd   time.Time
	WorkoutName  string
	Zone1Mins    int32
	Zone2Mins    int32
	Zone3Mins    int32
	Strain       int32
	UserID       uuid.UUID
}

type MeditationSession struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MeditationStart time.Time
	MeditationEnd   time.Time
	StartingHr      int32
	EndingHr        int32
	UserID          uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type SleepSession struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SleepStart        time.Time
	SleepEnd          time.Time
	RemDurationMins   int32
	LightDurationMins int32
	DeepDurationMins  int32
	UserID            uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
