// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sleep.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSleepSession = `-- name: CreateSleepSession :one
INSERT INTO sleep_sessions (id, created_at, updated_at, sleep_start, sleep_end, rem_duration_mins, light_duration_mins, deep_duration_mins, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, sleep_start, sleep_end, rem_duration_mins, light_duration_mins, deep_duration_mins, user_id
`

type CreateSleepSessionParams struct {
	SleepStart        time.Time
	SleepEnd          time.Time
	RemDurationMins   int32
	LightDurationMins int32
	DeepDurationMins  int32
	UserID            uuid.UUID
}

func (q *Queries) CreateSleepSession(ctx context.Context, arg CreateSleepSessionParams) (SleepSession, error) {
	row := q.db.QueryRowContext(ctx, createSleepSession,
		arg.SleepStart,
		arg.SleepEnd,
		arg.RemDurationMins,
		arg.LightDurationMins,
		arg.DeepDurationMins,
		arg.UserID,
	)
	var i SleepSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SleepStart,
		&i.SleepEnd,
		&i.RemDurationMins,
		&i.LightDurationMins,
		&i.DeepDurationMins,
		&i.UserID,
	)
	return i, err
}

const querySleepSession = `-- name: QuerySleepSession :one
SELECT id, created_at, updated_at, sleep_start, sleep_end, rem_duration_mins, light_duration_mins, deep_duration_mins, user_id FROM sleep_sessions WHERE id = $1
`

func (q *Queries) QuerySleepSession(ctx context.Context, id uuid.UUID) (SleepSession, error) {
	row := q.db.QueryRowContext(ctx, querySleepSession, id)
	var i SleepSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SleepStart,
		&i.SleepEnd,
		&i.RemDurationMins,
		&i.LightDurationMins,
		&i.DeepDurationMins,
		&i.UserID,
	)
	return i, err
}

const queryUserSleepSessions = `-- name: QueryUserSleepSessions :many
SELECT id, created_at, updated_at, sleep_start, sleep_end, rem_duration_mins, light_duration_mins, deep_duration_mins, user_id FROM sleep_sessions WHERE user_id = $1
`

func (q *Queries) QueryUserSleepSessions(ctx context.Context, userID uuid.UUID) ([]SleepSession, error) {
	rows, err := q.db.QueryContext(ctx, queryUserSleepSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SleepSession
	for rows.Next() {
		var i SleepSession
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SleepStart,
			&i.SleepEnd,
			&i.RemDurationMins,
			&i.LightDurationMins,
			&i.DeepDurationMins,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSleeps = `-- name: RemoveSleeps :exec
DELETE FROM sleep_sessions
`

func (q *Queries) RemoveSleeps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeSleeps)
	return err
}
