// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, password_hash)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, email, password_hash
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const queryUserEmail = `-- name: QueryUserEmail :one
SELECT id, created_at, updated_at, email, password_hash FROM users WHERE email = $1
`

func (q *Queries) QueryUserEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, queryUserEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const removeUsers = `-- name: RemoveUsers :exec
DELETE FROM users
`

func (q *Queries) RemoveUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeUsers)
	return err
}
