---
- name: Server Setup
  hosts: all
  become: true

  vars:
    packages:
      - nginx
      - mosquitto
      - curl
      - vim
      - tmux
      - isc-dhcp-server
    services:
      - nginx
      - mosquitto
      - isc-dhcp-server

  tasks:
  - name: Update APT cache
    ansible.builtin.apt:
      update_cache: yes
    changed_when: no

  - name: Install Packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"

  - name: Enable Services
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: "{{ item }}"
    loop: "{{ services }}"
