---
- name: Server Setup
  hosts: all
  become: true

  vars:
    packages:
      - nginx
      - mosquitto
      - curl
      - vim
      - tmux
      - isc-dhcp-server
    services:
      - nginx
      - mosquitto
      - isc-dhcp-server
    users:
      - millie
      - haley
      - admin
    groups:
      - devops
      - security
      - developers

  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: 'https://github.com/cantr1/ProfessionalPortfolio.git'
        dest: /home/kelz

    - name: Install Dependencies
      ansible.builtin.import_tasks: 
        tasks/install_dependencies.yml

    - name: Setup Users
      ansible.builtin.import_tasks:
        tasks/setup_user_groups.yml
