---
- name: Server Setup
  hosts: all
  become: true

  vars:
    packages:
      - mosquitto
      - mosquitto-clients
      - curl
      - vim
      - tmux
      - isc-dhcp-server
    services:
      - mosquitto
      - isc-dhcp-server
    users:
      - millie
      - haley
      - admin
    groups:
      - devops
      - security
      - developers

  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: 'https://github.com/cantr1/ProfessionalPortfolio.git'
        dest: /home/kelz

    - name: Install Dependencies
      ansible.builtin.import_tasks: 
        tasks/install_dependencies.yml

    - name: Setup Users
      ansible.builtin.import_tasks:
        tasks/setup_user_groups.yml
    
    - name: Setup Services
      ansible.builtin.import_tasks:
        tasks/setup_services.yml

    - name: Harden Server
      ansible.builtin.shell: "bash /home/kelz/ProfessionalPortfolio/BashAnvil/security/apply_hardening.sh"

    - name: Audit Hardening
      ansible.builtin.shell: "bash /home/kelz/ProfessionalPortfolio/BashAnvil/security/check_hardening.sh"
      register: hardening_check

    - name: Display Output of Server Hardening
      ansible.builtin.debug:
        msg: "{{ hardening_check.stdout }}"

    - name: Run Tests
      ansible.builtin.shell: "bash /home/kelz/ProfessionalPortfolio/BashAnvil/runner.sh"
      register: tests

    - name: Display Output of Tests
      ansible.builtin.debug:
        msg: "{{ tests.stdout }}"

    - name: Setup Cron Job for MQTT Reporting
      ansible.builtin.cron:
        name: Publish System Data to MQTT Broker
        minute: "/10"
        user: kelz
        job: mosquitto_pub -t system/"$(hostname)" -m "$(python3 /home/kelz/ProfessionalPortfolio/BashAnvil/system_data.py)" -h 192.168.1.124 -p 1883

