// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_registrations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO class_registrations (user_id, session_id, created_at, status)
VALUES (
    $1,
    $2,
    NOW(),
    $3
)
RETURNING user_id, session_id, created_at, status
`

type CreateRegistrationParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
	Status    string
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (ClassRegistration, error) {
	row := q.db.QueryRowContext(ctx, createRegistration, arg.UserID, arg.SessionID, arg.Status)
	var i ClassRegistration
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deleteUserSessionRegistration = `-- name: DeleteUserSessionRegistration :exec
DELETE FROM class_registrations
WHERE user_id = $1 AND session_id = $2
`

type DeleteUserSessionRegistrationParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) DeleteUserSessionRegistration(ctx context.Context, arg DeleteUserSessionRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessionRegistration, arg.UserID, arg.SessionID)
	return err
}

const querySessionIDRegistrations = `-- name: QuerySessionIDRegistrations :many
SELECT user_id, session_id, created_at, status FROM class_registrations WHERE session_id = $1
`

func (q *Queries) QuerySessionIDRegistrations(ctx context.Context, sessionID uuid.UUID) ([]ClassRegistration, error) {
	rows, err := q.db.QueryContext(ctx, querySessionIDRegistrations, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassRegistration
	for rows.Next() {
		var i ClassRegistration
		if err := rows.Scan(
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUserIDRegistrations = `-- name: QueryUserIDRegistrations :many
SELECT user_id, session_id, created_at, status FROM class_registrations WHERE user_id = $1
`

func (q *Queries) QueryUserIDRegistrations(ctx context.Context, userID uuid.UUID) ([]ClassRegistration, error) {
	rows, err := q.db.QueryContext(ctx, queryUserIDRegistrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassRegistration
	for rows.Next() {
		var i ClassRegistration
		if err := rows.Scan(
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRegistrations = `-- name: RemoveRegistrations :exec
DELETE FROM class_registrations
`

func (q *Queries) RemoveRegistrations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeRegistrations)
	return err
}
