// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ClassRegistration struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
	CreatedAt time.Time
	Status    string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Session struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	StartTime    time.Time
	EndTime      time.Time
	InstructorID uuid.UUID
	Difficulty   int32
	ClassSize    int32
	Description  string
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	Name         string
	PasswordHash string
	IsInstructor sql.NullBool
}
