// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description
`

type CreateSessionParams struct {
	StartTime    time.Time
	EndTime      time.Time
	InstructorID uuid.UUID
	Difficulty   int32
	ClassSize    int32
	Description  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.StartTime,
		arg.EndTime,
		arg.InstructorID,
		arg.Difficulty,
		arg.ClassSize,
		arg.Description,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.InstructorID,
		&i.Difficulty,
		&i.ClassSize,
		&i.Description,
	)
	return i, err
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions
`

func (q *Queries) GetAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSessionsWithInstructor = `-- name: GetAllSessionsWithInstructor :many
SELECT
    sessions.id,
    sessions.created_at,
    sessions.updated_at,
    sessions.start_time,
    sessions.end_time,
    sessions.instructor_id,
    users.name AS instructor_name,
    sessions.difficulty,
    sessions.class_size,
    sessions.description
FROM sessions
JOIN users ON users.id = sessions.instructor_id
`

type GetAllSessionsWithInstructorRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StartTime      time.Time
	EndTime        time.Time
	InstructorID   uuid.UUID
	InstructorName string
	Difficulty     int32
	ClassSize      int32
	Description    string
}

func (q *Queries) GetAllSessionsWithInstructor(ctx context.Context) ([]GetAllSessionsWithInstructorRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessionsWithInstructor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSessionsWithInstructorRow
	for rows.Next() {
		var i GetAllSessionsWithInstructorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.InstructorName,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAvailableSessionsDifficulty = `-- name: QueryAvailableSessionsDifficulty :many
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions WHERE difficulty = $1
`

func (q *Queries) QueryAvailableSessionsDifficulty(ctx context.Context, difficulty int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, queryAvailableSessionsDifficulty, difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAvailableSessionsInstructor = `-- name: QueryAvailableSessionsInstructor :many
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions WHERE instructor_id = $1
`

func (q *Queries) QueryAvailableSessionsInstructor(ctx context.Context, instructorID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, queryAvailableSessionsInstructor, instructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySessionID = `-- name: QuerySessionID :one
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions WHERE id = $1
`

func (q *Queries) QuerySessionID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, querySessionID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.InstructorID,
		&i.Difficulty,
		&i.ClassSize,
		&i.Description,
	)
	return i, err
}

const querySessionIDWithInstructor = `-- name: QuerySessionIDWithInstructor :one
SELECT
    sessions.id,
    sessions.created_at,
    sessions.updated_at,
    sessions.start_time,
    sessions.end_time,
    sessions.instructor_id,
    users.name AS instructor_name,
    sessions.difficulty,
    sessions.class_size,
    sessions.description
FROM sessions
JOIN users ON users.id = sessions.instructor_id
WHERE sessions.id = $1
`

type QuerySessionIDWithInstructorRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StartTime      time.Time
	EndTime        time.Time
	InstructorID   uuid.UUID
	InstructorName string
	Difficulty     int32
	ClassSize      int32
	Description    string
}

func (q *Queries) QuerySessionIDWithInstructor(ctx context.Context, id uuid.UUID) (QuerySessionIDWithInstructorRow, error) {
	row := q.db.QueryRowContext(ctx, querySessionIDWithInstructor, id)
	var i QuerySessionIDWithInstructorRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.InstructorID,
		&i.InstructorName,
		&i.Difficulty,
		&i.ClassSize,
		&i.Description,
	)
	return i, err
}

const querySessionsDifficulty = `-- name: QuerySessionsDifficulty :many
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions WHERE difficulty = $1
`

func (q *Queries) QuerySessionsDifficulty(ctx context.Context, difficulty int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, querySessionsDifficulty, difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySessionsInstructor = `-- name: QuerySessionsInstructor :many
SELECT id, created_at, updated_at, start_time, end_time, instructor_id, difficulty, class_size, description FROM sessions WHERE instructor_id = $1
`

func (q *Queries) QuerySessionsInstructor(ctx context.Context, instructorID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, querySessionsInstructor, instructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.InstructorID,
			&i.Difficulty,
			&i.ClassSize,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSessions = `-- name: RemoveSessions :exec
DELETE FROM sessions
`

func (q *Queries) RemoveSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeSessions)
	return err
}
