---
- name: Execute SEL Hardening Playbook
  hosts: SEL_Targets
  roles:
  - SEL_Hardening
  tags: SEL

- name: Execute AMA Hardening Playbook
  hosts: AMA_Targets
  roles:
  - AMA_Hardening
  tags: AMA

- name: Execute FAB Hardening Playbook
  hosts: FAB_Targets
  roles:
  - FAB_Hardening
  tags: FAB  