---
- name: Execute Audit and Conditionally Harden
  hosts: all
  become: true

  tasks:
  - name: Run audit script
    ansible.builtin.script: "/etc/ansible/Scripts/audit_hardening.sh"
    register: audit_result
    ignore_errors: true
    changed_when: false

  - name: Print audit output
    ansible.builtin.debug:
      var: audit_result.stdout_lines

  - name: Run hardening script if audit failed
    ansible.builtin.script: "/etc/ansible/Scripts/hardening_script.sh"
    when: audit_result.rc != 0

  - name: Debug Message
    ansible.builtin.debug:
      msg: "Audit completed."