# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the API contents into the container
COPY API/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

copy API/.

# Command to run the application
CMD ["fastapi", "run", "main.py"]
