from redis:7

# Copy config
COPY redis.conf /usr/local/etc/redis/redis.conf

# Run the server
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# Use the following commands to build redis container
# docker build -t redis-dev .
# docker run --name redis-server -p 6379:6379 -d redis-dev